<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'd08294d0776644b992f401e6b07bab98',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'DATABASE_URL' => 'mysql://e1232614_darkRoastedCoffee:uKjsPt7yFL9D@techinfo-cstj.ca:3306/e1232614_dark_roasted_coffeev2',
);
